<?php

declare(strict_types=1);

namespace App\Domain\CropRecommendation\Catalog;

/**
 * Mock fruit entries: agronomic scoring inputs keyed by taxonomy slug.
 */
final class MockFruitEntries
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            [
                'slug' => 'watermelon',
                'name' => 'Watermelon (Pakwan)',
                'ideal_soils' => ['sandy', 'silt', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tarlac', 'pampanga', 'pangasinan', 'central luzon'],
                'min_area' => 0.1, 'max_area' => 6.0,
                'yield_ha' => 26.0, 'unit' => 'tons',
                'confidence' => 88,
                'soil_reason' => 'Warm, quick-draining :soil soil promotes high sugar content (Brix) and prevents fungal root-rot during fruit set.',
                'loc_reason' => 'High summer cash turnover and strong demand across wholesale markets in :loc.',
            ],
            [
                'slug' => 'strawberry',
                'name' => 'Highland Strawberries',
                'ideal_soils' => ['loamy', 'peat'],
                'unsuitable_soils' => ['clay', 'chalky'],
                'regions' => ['benguet', 'baguio', 'cordillera'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 24.0, 'unit' => 'tons',
                'confidence' => 97,
                'soil_reason' => 'Acidic, humus-rich :soil soil fuels continuous sweet berry flowering and root aeration.',
                'loc_reason' => 'Famous high-altitude agro-climate and agritourism market in :loc.',
            ],
            [
                'slug' => 'pineapple',
                'name' => 'Pineapple (Pinya)',
                'ideal_soils' => ['peat', 'sandy', 'loamy'],
                'unsuitable_soils' => ['clay', 'chalky'],
                'regions' => ['cavite', 'laguna', 'bukidnon', 'camarines'],
                'min_area' => 0.2, 'max_area' => 15.0,
                'yield_ha' => 36.0, 'unit' => 'tons',
                'confidence' => 91,
                'soil_reason' => 'Prefers acidic, free-draining :soil soil, producing high-sugar, sun-ripened fruit crowns.',
                'loc_reason' => 'Flourishes in the well-drained volcanic/sub-tropical conditions of :loc.',
            ],
            [
                'slug' => 'coconut',
                'name' => 'Commercial Coconut Grove',
                'ideal_soils' => ['sandy', 'loamy', 'clay'],
                'unsuitable_soils' => [],
                'regions' => ['quezon', 'davao', 'bicol', 'mindanao', 'visayas'],
                'min_area' => 2.0, 'max_area' => 100.0,
                'yield_ha' => 9500, 'unit' => 'nuts',
                'confidence' => 91,
                'soil_reason' => 'Deep-reaching root system anchors effortlessly in :soil terrain, sustaining multi-decade nut yields.',
                'loc_reason' => 'Proximity to copra processing facilities and coconut oil extraction plants across :loc.',
            ],
            [
                'slug' => 'calamansi',
                'name' => 'Calamansi',
                'ideal_soils' => ['loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['quezon', 'batangas', 'mindoro', 'central luzon'],
                'min_area' => 0.1, 'max_area' => 5.0,
                'yield_ha' => 12.0, 'unit' => 'tons',
                'confidence' => 89,
                'soil_reason' => 'Well-drained :soil soil keeps feeder roots healthy for year-round fruiting flushes.',
                'loc_reason' => 'Ubiquitous condiment crop with daily wet-market demand across :loc.',
            ],
            [
                'slug' => 'pomelo',
                'name' => 'Pomelo (Suha)',
                'ideal_soils' => ['loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['davao', 'quezon', 'batangas'],
                'min_area' => 0.2, 'max_area' => 10.0,
                'yield_ha' => 18.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Deep :soil profiles anchor long-lived trees and sweeten heavy fruit.',
                'loc_reason' => 'Premium festive fruit with strong regional wholesale channels in :loc.',
            ],
            [
                'slug' => 'dalandan',
                'name' => 'Orange (Dalandan)',
                'ideal_soils' => ['loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['quezon', 'laguna', 'batangas'],
                'min_area' => 0.1, 'max_area' => 5.0,
                'yield_ha' => 14.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Slightly acidic :soil soil develops aromatic, juicy segments.',
                'loc_reason' => 'Juice-industry and fresh-market staple sourced across :loc.',
            ],
            [
                'slug' => 'banana',
                'name' => 'Banana (Lakatan)',
                'ideal_soils' => ['loamy', 'clay'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['davao', 'mindanao', 'quezon'],
                'min_area' => 0.2, 'max_area' => 10.0,
                'yield_ha' => 25.0, 'unit' => 'tons',
                'confidence' => 89,
                'soil_reason' => 'Moisture-retentive :soil soil sustains rapid sucker growth and heavy bunches.',
                'loc_reason' => 'Top dessert cultivar with export-grade buyers operating in :loc.',
            ],
            [
                'slug' => 'mango',
                'name' => 'Mango (Carabao)',
                'ideal_soils' => ['sandy', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['pangasinan', 'ilocos', 'cebu', 'guimaras'],
                'min_area' => 0.3, 'max_area' => 15.0,
                'yield_ha' => 11.0, 'unit' => 'tons',
                'confidence' => 88,
                'soil_reason' => 'Deep, well-drained :soil ground encourages intense flowering and fiberless flesh.',
                'loc_reason' => 'Flagship export fruit with mature consolidator networks across :loc.',
            ],
            [
                'slug' => 'cantaloupe',
                'name' => 'Cantaloupe (Melon)',
                'ideal_soils' => ['sandy', 'loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tarlac', 'pangasinan', 'central luzon'],
                'min_area' => 0.1, 'max_area' => 4.0,
                'yield_ha' => 21.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Warm :soil beds ripen fragrant, netted fruit with high sugar.',
                'loc_reason' => 'Summer cash crop moving fast through wholesale bagsakan in :loc.',
            ],
            [
                'slug' => 'dragon-fruit',
                'name' => 'Dragon Fruit',
                'ideal_soils' => ['sandy', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['ilocos', 'pangasinan', 'cebu'],
                'min_area' => 0.1, 'max_area' => 5.0,
                'yield_ha' => 20.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Lean, fast-draining :soil soil suits cactus roots and trellised posts.',
                'loc_reason' => 'High-margin novelty fruit with growing supermarket shelf space in :loc.',
            ],
            [
                'slug' => 'mulberry',
                'name' => 'Mulberry',
                'ideal_soils' => ['loamy', 'sandy'],
                'unsuitable_soils' => [],
                'regions' => ['benguet', 'la union', 'central luzon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 8.0, 'unit' => 'tons',
                'confidence' => 84,
                'soil_reason' => 'Adaptable roots establish quickly in :soil soil for continuous berry flushes.',
                'loc_reason' => 'Emerging jam and wine ingredient crop around :loc.',
            ],
            [
                'slug' => 'blueberry',
                'name' => 'Blueberry (Highland)',
                'ideal_soils' => ['peat', 'sandy'],
                'unsuitable_soils' => ['clay', 'chalky'],
                'regions' => ['benguet', 'baguio', 'cordillera'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 9.0, 'unit' => 'tons',
                'confidence' => 85,
                'soil_reason' => 'Acidic, airy :soil media mirrors native highland heath conditions.',
                'loc_reason' => 'Ultra-premium berry for U-pick agritourism in the highlands of :loc.',
            ],
        ];
    }
}
