<?php

declare(strict_types=1);

namespace App\Domain\CropRecommendation\Catalog;

/**
 * Mock vegetable entries: agronomic scoring inputs keyed by taxonomy slug.
 * Verbatim move of the legacy matrix plus taxonomy-gap coverage crops.
 */
final class MockVegetableEntries
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function all(): array
    {
        return [
            [
                'slug' => 'sweet-potato',
                'name' => 'Sweet Potato (Camote)',
                'ideal_soils' => ['sandy', 'loamy', 'peat'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tarlac', 'pampanga', 'central luzon', 'bicol'],
                'min_area' => 0.05, 'max_area' => 10.0,
                'yield_ha' => 14.5, 'unit' => 'tons',
                'confidence' => 93,
                'soil_reason' => 'Loose :soil soil prevents subterranean compaction, enabling tubers to expand smoothly without root deformities or rot.',
                'loc_reason' => 'Capitalizes on high commercial demand and regional root-crop processing hubs in :loc.',
            ],
            [
                'slug' => 'peanut',
                'name' => 'Peanuts (Mani)',
                'ideal_soils' => ['sandy', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tarlac', 'pangasinan', 'ilocos', 'central luzon'],
                'min_area' => 0.05, 'max_area' => 5.0,
                'yield_ha' => 2.8, 'unit' => 'tons',
                'confidence' => 89,
                'soil_reason' => 'Porous, aerated :soil soil allows flower pegs to easily penetrate beneath the surface to develop pods while fixing vital soil nitrogen.',
                'loc_reason' => 'Strong local wholesale and food processor buying networks in :loc.',
            ],
            [
                'slug' => 'cassava',
                'name' => 'Cassava (Kamoteng Kahoy)',
                'ideal_soils' => ['sandy', 'peat', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tarlac', 'mindanao', 'visayas', 'central luzon'],
                'min_area' => 0.2, 'max_area' => 20.0,
                'yield_ha' => 22.0, 'unit' => 'tons',
                'confidence' => 85,
                'soil_reason' => 'Drought-hardy starch crop that thrives with minimal inputs in loose :soil ground with effortless harvest pulling.',
                'loc_reason' => 'Steady industrial feed and starch mill demand in :loc.',
            ],
            [
                'slug' => 'taro',
                'name' => 'Taro (Gabi)',
                'ideal_soils' => ['clay', 'peat', 'silt'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['tarlac', 'bicol', 'quezon', 'central luzon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 13.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Semi-aquatic root crop that thrives in wet, heavy :soil soil where standard vegetables would suffocate.',
                'loc_reason' => 'High regional culinary demand for both leaves and corms in :loc.',
            ],
            [
                'slug' => 'red-onion',
                'name' => 'Red Creole Onions (Sibuyas)',
                'ideal_soils' => ['silt', 'loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['nueva ecija', 'pangasinan', 'central luzon'],
                'min_area' => 0.05, 'max_area' => 4.0,
                'yield_ha' => 16.5, 'unit' => 'tons',
                'confidence' => 95,
                'soil_reason' => 'Fine, non-crusting :soil soil allows onion bulbs to expand symmetrically without constriction.',
                'loc_reason' => 'Direct proximity to Bongabon/Nueva Ecija cold-storage and national wholesale dispatch in :loc.',
            ],
            [
                'slug' => 'tomato',
                'name' => 'Tomatoes (Kamatis)',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['central luzon', 'ilocos', 'nueva ecija', 'bulacan'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 22.0, 'unit' => 'tons',
                'confidence' => 90,
                'soil_reason' => 'Balanced :soil soil provides optimal drainage and steady capillary water, suppressing bacterial wilt.',
                'loc_reason' => 'High daily turnover and strong sales through local fresh wet markets in :loc.',
            ],
            [
                'slug' => 'eggplant',
                'name' => 'Eggplant (Talong)',
                'ideal_soils' => ['loamy', 'silt', 'clay'],
                'unsuitable_soils' => [],
                'regions' => ['pangasinan', 'nueva ecija', 'central luzon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 19.0, 'unit' => 'tons',
                'confidence' => 89,
                'soil_reason' => 'Resilient taproot system thrives in nutrient-dense :soil soil, delivering continuous weekly flushes.',
                'loc_reason' => 'Year-round dietary staple with stable farm-gate prices in :loc.',
            ],
            [
                'slug' => 'ampalaya',
                'name' => 'Bitter Gourd (Ampalaya)',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['pampanga', 'bulacan', 'nueva ecija', 'central luzon'],
                'min_area' => 0.05, 'max_area' => 2.0,
                'yield_ha' => 15.0, 'unit' => 'tons',
                'confidence' => 88,
                'soil_reason' => 'High organic aeration in :soil soil supports rapid vine climbing and disease-free flowering.',
                'loc_reason' => 'Premium-priced vegetable favored by commercial traders across :loc.',
            ],
            [
                'slug' => 'chili',
                'name' => 'Hot Chili (Siling Labuyo)',
                'ideal_soils' => ['peat', 'loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['bicol', 'central luzon', 'tarlac', 'batangas'],
                'min_area' => 0.02, 'max_area' => 1.5,
                'yield_ha' => 8.5, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Warm, organic-rich :soil soil stimulates concentrated capsaicin synthesis and continuous pod set.',
                'loc_reason' => 'Outstanding value per square meter, offering high income density on compact plots in :loc.',
            ],
            [
                'slug' => 'cabbage',
                'name' => 'Highland Cabbage (Repolyo)',
                'ideal_soils' => ['loamy', 'clay', 'silt'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['benguet', 'baguio', 'bukidnon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 28.0, 'unit' => 'tons',
                'confidence' => 92,
                'soil_reason' => 'Moisture-retaining :soil soil produces dense, compact heads without inner leaf tip-burn.',
                'loc_reason' => 'Core production zone supplying major metropolitan trading centers from :loc.',
            ],
            [
                'slug' => 'mungbean',
                'name' => 'Mungbean (Munggo / Balatong)',
                'ideal_soils' => ['sandy', 'loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tarlac', 'pangasinan', 'central luzon', 'ilocos'],
                'min_area' => 0.1, 'max_area' => 10.0,
                'yield_ha' => 1.4, 'unit' => 'tons',
                'confidence' => 90,
                'soil_reason' => 'Short-duration legume that enriches :soil soil with fixed atmospheric nitrogen between primary rotations.',
                'loc_reason' => 'High staple consumer demand and active wholesale consolidation hubs across :loc.',
            ],
            [
                'slug' => 'sitaw',
                'name' => 'String Beans (Sitaw)',
                'ideal_soils' => ['loamy', 'silt', 'clay'],
                'unsuitable_soils' => [],
                'regions' => ['central luzon', 'tarlac', 'nueva ecija', 'pampanga'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 12.5, 'unit' => 'tons',
                'confidence' => 89,
                'soil_reason' => 'Rapid vine development in fertile :soil ground with high continuous pod yields on trellises.',
                'loc_reason' => 'Consistent daily turnover through regional trading posts and public markets in :loc.',
            ],
            [
                'slug' => 'okra',
                'name' => "Okra (Lady's Finger)",
                'ideal_soils' => ['loamy', 'clay', 'sandy'],
                'unsuitable_soils' => [],
                'regions' => ['central luzon', 'tarlac', 'pampanga', 'nueva ecija'],
                'min_area' => 0.05, 'max_area' => 4.0,
                'yield_ha' => 10.0, 'unit' => 'tons',
                'confidence' => 88,
                'soil_reason' => 'Hardy taproot tolerates both wet and dry cycles in :soil ground while continuously bearing tender pods.',
                'loc_reason' => 'Growing export and domestic fresh processing linkages operating in :loc.',
            ],
            [
                'slug' => 'squash',
                'name' => 'Squash (Kalabasa)',
                'ideal_soils' => ['loamy', 'silt', 'clay'],
                'unsuitable_soils' => [],
                'regions' => ['central luzon', 'nueva ecija', 'tarlac', 'pangasinan'],
                'min_area' => 0.1, 'max_area' => 5.0,
                'yield_ha' => 20.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Wide trailing canopy shades :soil soil, suppressing weed growth and conserving root-zone moisture.',
                'loc_reason' => 'Long post-harvest shelf life providing price stability during transport across :loc.',
            ],
            [
                'slug' => 'ginger',
                'name' => 'Native Ginger (Luya)',
                'ideal_soils' => ['loamy', 'sandy', 'peat'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['central luzon', 'batangas', 'quezon', 'bicol'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 18.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Friable, organic-rich :soil soil prevents rhizome rot and enables massive underground cluster expansion.',
                'loc_reason' => 'Lucrative cash-density per square meter in local culinary and herbal markets across :loc.',
            ],
            [
                'slug' => 'garlic',
                'name' => 'Garlic (Bawang)',
                'ideal_soils' => ['sandy', 'silt', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['ilocos', 'pangasinan', 'central luzon', 'tarlac'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 5.5, 'unit' => 'tons',
                'confidence' => 85,
                'soil_reason' => 'Well-draining, non-crusting :soil soil facilitates uniform bulb cloves without fungal damping.',
                'loc_reason' => 'High-value commodity enjoying premium local market pricing across :loc.',
            ],
            [
                'slug' => 'cucumber',
                'name' => 'Cucumber (Pipino)',
                'ideal_soils' => ['loamy', 'silt', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['central luzon', 'nueva ecija', 'pampanga', 'tarlac'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 25.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Fast-rooting crop that extracts balanced moisture from aerated :soil beds without root stagnation.',
                'loc_reason' => 'Short 45-day turnaround delivering quick seasonal cash flow to farmers in :loc.',
            ],
            [
                'slug' => 'malunggay',
                'name' => 'Commercial Malunggay (Moringa)',
                'ideal_soils' => ['sandy', 'loamy', 'chalky'],
                'unsuitable_soils' => ['clay', 'peat'],
                'regions' => ['central luzon', 'pangasinan', 'ilocos', 'tarlac'],
                'min_area' => 0.1, 'max_area' => 10.0,
                'yield_ha' => 12.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Extremely drought-tolerant deep taproot thrives even in poor, well-draining :soil soils.',
                'loc_reason' => 'Surging nutraceutical powder and food-grade processor demand across :loc.',
            ],
            [
                'slug' => 'pechay',
                'name' => 'Pechay (Bok Choy)',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['benguet', 'baguio', 'central luzon', 'tagaytay'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 9.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Moisture-holding :soil soil keeps fast-growing leaves crisp and tender through harvest.',
                'loc_reason' => 'Everyday market staple with rapid 30-day cropping cycles in :loc.',
            ],
            [
                'slug' => 'lettuce',
                'name' => 'Lettuce',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['benguet', 'baguio', 'tagaytay'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 11.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Cool, friable :soil beds prevent bitterness and tip-burn in delicate heads.',
                'loc_reason' => 'Strong salad-bowl and restaurant demand supplied from highland farms in :loc.',
            ],
            [
                'slug' => 'broccoli',
                'name' => 'Broccoli',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['benguet', 'baguio', 'bukidnon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 13.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Fertile :soil soil feeds tight, heavy curds without hollow stems.',
                'loc_reason' => 'High-value highland vegetable with steady supermarket contracts from :loc.',
            ],
            [
                'slug' => 'cauliflower',
                'name' => 'Cauliflower',
                'ideal_soils' => ['loamy', 'silt', 'clay'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['benguet', 'baguio', 'bukidnon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 16.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Even moisture in :soil soil keeps curds white and compact to harvest.',
                'loc_reason' => 'Premium cool-season crop traded through highland consolidation centers in :loc.',
            ],
            [
                'slug' => 'celery',
                'name' => 'Celery',
                'ideal_soils' => ['loamy', 'silt', 'peat'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['benguet', 'baguio', 'tagaytay'],
                'min_area' => 0.02, 'max_area' => 1.0,
                'yield_ha' => 30.0, 'unit' => 'tons',
                'confidence' => 85,
                'soil_reason' => 'Constantly moist, organic :soil soil grows crisp, string-free stalks.',
                'loc_reason' => 'Niche highland crop with reliable hotel and restaurant buyers near :loc.',
            ],
            [
                'slug' => 'carrot',
                'name' => 'Carrots',
                'ideal_soils' => ['sandy', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['benguet', 'baguio', 'bukidnon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 18.0, 'unit' => 'tons',
                'confidence' => 88,
                'soil_reason' => 'Deep, stone-free :soil soil lets roots grow long and straight without forking.',
                'loc_reason' => 'Staple highland crop with daily trading-post volume in :loc.',
            ],
            [
                'slug' => 'potato',
                'name' => 'White Potato (Patatas)',
                'ideal_soils' => ['loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['benguet', 'bukidnon', 'davao'],
                'min_area' => 0.05, 'max_area' => 5.0,
                'yield_ha' => 20.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Loose, well-drained :soil soil keeps tubers clean and rot-free to bulking.',
                'loc_reason' => 'Contracted by chipping processors sourcing from :loc.',
            ],
            [
                'slug' => 'bell-pepper',
                'name' => 'Bell Pepper',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['benguet', 'cavite', 'bukidnon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 12.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Fertile, well-drained :soil soil sets thick-walled fruit over a long picking season.',
                'loc_reason' => 'High-value greenhouse and open-field crop with supermarket pull from :loc.',
            ],
            [
                'slug' => 'mustard',
                'name' => 'Mustard Greens (Mustasa)',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['laguna', 'quezon', 'rizal'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 9.0, 'unit' => 'tons',
                'confidence' => 87,
                'soil_reason' => 'Moist, nitrogen-rich :soil soil pushes fast, tender leaf growth for quick harvests.',
                'loc_reason' => 'Everyday lowland leafy green with nonstop wet-market demand in :loc.',
            ],
            [
                'slug' => 'shallot',
                'name' => 'Shallots (Sibuyas Tagalog)',
                'ideal_soils' => ['silt', 'loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['ilocos', 'pangasinan', 'cagayan'],
                'min_area' => 0.05, 'max_area' => 4.0,
                'yield_ha' => 14.0, 'unit' => 'tons',
                'confidence' => 88,
                'soil_reason' => 'Friable :soil soil lets clustered bulbs size up without splitting.',
                'loc_reason' => 'Native multiplier onion prized by processors buying from :loc.',
            ],
            [
                'slug' => 'sayote',
                'name' => 'Chayote (Sayote)',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['benguet', 'cavite', 'quezon'],
                'min_area' => 0.05, 'max_area' => 3.0,
                'yield_ha' => 25.0, 'unit' => 'tons',
                'confidence' => 86,
                'soil_reason' => 'Deep, fertile :soil soil feeds a vigorous perennial vine for months of picking.',
                'loc_reason' => 'Prolific trellis crop that rides affordable prices into :loc markets.',
            ],
            [
                'slug' => 'kangkong',
                'name' => 'Water Spinach (Kangkong)',
                'ideal_soils' => ['clay', 'silt', 'peat'],
                'unsuitable_soils' => ['sandy'],
                'regions' => ['laguna', 'pampanga', 'bicol'],
                'min_area' => 0.02, 'max_area' => 2.0,
                'yield_ha' => 30.0, 'unit' => 'tons',
                'confidence' => 90,
                'soil_reason' => 'Wet, heavy :soil soil suits this semi-aquatic green that cut-and-comes-again.',
                'loc_reason' => 'Fastest cash-turn leafy crop around the waterways of :loc.',
            ],
            [
                'slug' => 'dill',
                'name' => 'Dill',
                'ideal_soils' => ['loamy', 'sandy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['benguet', 'tagaytay', 'baguio'],
                'min_area' => 0.01, 'max_area' => 1.0,
                'yield_ha' => 4.0, 'unit' => 'tons',
                'confidence' => 82,
                'soil_reason' => 'Light :soil soil grows feathery, aromatic fronds for repeat cutting.',
                'loc_reason' => 'Specialty culinary herb supplied to metro restaurants from :loc.',
            ],
            [
                'slug' => 'lemongrass',
                'name' => 'Lemongrass (Tanglad)',
                'ideal_soils' => ['sandy', 'loamy'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['quezon', 'bicol', 'palawan'],
                'min_area' => 0.02, 'max_area' => 3.0,
                'yield_ha' => 15.0, 'unit' => 'tons',
                'confidence' => 85,
                'soil_reason' => 'Lean, free-draining :soil soil concentrates the oils in each stalk.',
                'loc_reason' => 'Hardy perennial with oil and culinary buyers across :loc.',
            ],
            [
                'slug' => 'basil',
                'name' => 'Sweet Basil (Balanoy)',
                'ideal_soils' => ['loamy', 'silt'],
                'unsuitable_soils' => ['clay'],
                'regions' => ['tagaytay', 'cavite', 'laguna'],
                'min_area' => 0.01, 'max_area' => 1.0,
                'yield_ha' => 6.0, 'unit' => 'tons',
                'confidence' => 84,
                'soil_reason' => 'Warm, fertile :soil soil keeps bushes leafy through continuous harvest.',
                'loc_reason' => 'Fresh-herb staple for pesto makers and kitchens near :loc.',
            ],
        ];
    }
}
