<?php
/** @var array<string, mixed> $pack */
$e = fn (mixed $v): string => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$money = fn (float $v): string => 'PHP '.number_format($v, 2);
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, Helvetica, Arial, sans-serif; color: #1c1917; font-size: 12px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  h2 { font-size: 14px; border-bottom: 2px solid #4a8c42; padding-bottom: 4px; margin-top: 22px; }
  .subtitle { color: #57534e; margin: 0 0 12px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { text-align: left; padding: 6px 8px; border: 1px solid #d6d3d1; vertical-align: top; }
  th { background: #f5f5f4; width: 32%; }
  .check li { margin-bottom: 6px; list-style: none; }
  .check { padding-left: 0; }
  .steps li { margin-bottom: 8px; }
  .notice { background: #fef9c3; border: 1px solid #d49a20; padding: 10px 12px; margin-top: 18px; }
  .footer { margin-top: 24px; color: #78716c; font-size: 10px; }
</style>
</head>
<body>
<h1>YieldGrid PCIC Enrollment Pack</h1>
<p class="subtitle">Pre-filled summary for Philippine Crop Insurance Corporation enrollment &mdash; generated <?= $e($pack['generated_at']) ?></p>

<h2>Farmer</h2>
<table>
  <tr><th>Name</th><td><?= $e($pack['farmer_name']) ?></td></tr>
  <tr><th>Email</th><td><?= $e($pack['farmer_email']) ?></td></tr>
  <tr><th>Phone</th><td><?= $e($pack['farmer_phone']) ?></td></tr>
  <tr><th>RSBSA number</th><td><?= $e($pack['rsbsa_number']) ?></td></tr>
  <tr><th>RSBSA registered</th><td><?= $pack['rsbsa_registered'] ? 'Yes' : 'No — register at your Municipal Agriculturist Office first' ?></td></tr>
</table>

<h2>Farm &amp; Plot</h2>
<table>
  <tr><th>Farm</th><td><?= $e($pack['farm_name']) ?></td></tr>
  <tr><th>Location</th><td><?= $e($pack['farm_location']) ?></td></tr>
  <tr><th>Plot</th><td><?= $e($pack['plot_name']) ?></td></tr>
  <tr><th>Area</th><td><?= $e(number_format((float) $pack['plot_area_ha'], 2)) ?> ha</td></tr>
  <tr><th>Soil type</th><td><?= $e($pack['plot_soil_type']) ?></td></tr>
</table>

<h2>Insurance Request</h2>
<table>
  <tr><th>Program</th><td><?= $e($pack['program_label']) ?></td></tr>
  <tr><th>Season</th><td><?= $e($pack['season_label']) ?></td></tr>
  <tr><th>Estimated cover</th><td><?= $e($money((float) $pack['estimated_coverage_php'])) ?> (<?= $e(number_format((float) $pack['plot_area_ha'], 2)) ?> ha at <?= $e($money((float) $pack['coverage_per_hectare_php'])) ?>/ha)</td></tr>
</table>

<h2>Bring These to Your MAO</h2>
<ul class="check">
  <li>&#9744; This enrollment pack (printed)</li>
  <li>&#9744; Photocopy of RSBSA enrollment stub</li>
  <li>&#9744; One valid ID</li>
  <li>&#9744; Proof of land tillage (title, lease, or caretaker agreement)</li>
</ul>

<h2>Submission Steps</h2>
<ol class="steps">
  <li>Bring this pack and the requirements above to your Municipal Agriculturist Office.</li>
  <li>Fill out the PCIC application form with the assistance of the agricultural technologist.</li>
  <li>Wait for PCIC underwriting — you will receive a Certificate of Insurance Cover (CIC).</li>
  <li>Record your CIC number back in YieldGrid to activate claim tracking and reminders.</li>
</ol>

<div class="notice"><strong>Not an official PCIC document.</strong> This pack is an informational summary generated by YieldGrid. Program terms, coverage amounts, and requirements are set by PCIC and your MAO — confirm them before submitting.</div>

<p class="footer">Generated <?= $e($pack['generated_at']) ?> by YieldGrid. Estimates use <?= $e($money((float) $pack['coverage_per_hectare_php'])) ?> per hectare for total loss.</p>
</body>
</html>
